### ISSUE TITLE
Create products database

### ISSUE THREAD

**Issue by Katskiiii** [OnslowCollege/complex-techniques-rja-2024-annabelle-chloe-katarina#1]
- Create a table and appropriate columns for products in MySQL using a VSCode Extension (SQL Notebook).
- Link with other table(s) if appropriate.
- Insert products

**Comment by chloesypena** [comment]
I have finished "create products database", as I have successfully made and tested the table for it while also linking the table with others if appropriate. I have also inserted all products inside the table.
